// Oleksandr Tkachov 2021-2026

#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogRPGPlayerCharacter, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGInventory, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGItem, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGPlayerController, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGUIHUD, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGPhotoMode, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGMap, Verbose, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGMount, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGQuests, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogRPGSaving, Log, All);
