// Oleksandr Tkachov 2022-2023


#include "Utility/LogDefinitions.h"

DEFINE_LOG_CATEGORY(LogRPGPlayerCharacter);
DEFINE_LOG_CATEGORY(LogRPGInventory);
DEFINE_LOG_CATEGORY(LogRPGItem);
DEFINE_LOG_CATEGORY(LogRPGPlayerController);
DEFINE_LOG_CATEGORY(LogRPGUIHUD);
DEFINE_LOG_CATEGORY(LogRPGPhotoMode);
DEFINE_LOG_CATEGORY(LogRPGMap);
